document.writeln("	<!--site header start-->");
document.writeln("	<div class=\'site_head\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("			<h6 style=\'font-size: 10px;color: #fff; line-height: 12px;text-align: center;\'>北京科旺达信息技术有限公司是专注为企业提供软件技术开发，帮助企业提高核心竞争力和降低软件项目成本。</h6>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<!--menu header start-->");
document.writeln("	<div class=\'responsive_menu comNavList \' style=\'display: none;\'>");
document.writeln("		<ul class=\'main_menu visible-sm visible-xs\'>");
document.writeln("			<li class=\'index\'><a href=\'index.html\'>首页</a></li>");
document.writeln("			<li class=\'product\'><a href=\'product.html\'>产品中心</a></li>");
document.writeln("			<li class=\'case\'><a href=\'case.html\'>客户案例</a></li>");
document.writeln("			<li class=\'solution\'><a href=\'solution.html\'>解决方案</a></li>");
document.writeln("			<li class=\'news\'><a href=\'news.html\'>新闻专栏</a></li>");
document.writeln("			<li class=\'aptitude\'><a href=\'aptitude.html\'>企业资质</a></li>");
document.writeln("			<li class=\'about\'><a href=\'about.html\'>关于我们</a></li>");
document.writeln("			<li class=\'contact\'><a href=\'contact.html\'>联系我们</a></li>");
document.writeln("		</ul> ");
document.writeln("	</div>");
document.writeln("	<!--header box start-->");
document.writeln("	<div class=\'header_box clearfix\'>");
document.writeln("		<!--header start-->");
document.writeln("		<div class=\'container\'>");
document.writeln("			<div class=\'header col-md-12 visible-md visible-lg\'>");
document.writeln("				<div class=\'logo col-md-2\'>");
document.writeln("					<a href=\'http://www.kwangda.com\'><img src=\'images/head foot/logo.png\' alt=\'科旺达\'></a>");
document.writeln("				</div>");
document.writeln("				<!--logo-->");
document.writeln("				<div class=\'contact_item col-md-10\'>");
document.writeln("					<div class=\'contact_mini\'>");
document.writeln("						<div class=\'contact_icon_map\'>");
document.writeln("							<i class=\'glyphicon glyphicon-map-marker\' aria-hidden=\'true\'></i>");
document.writeln("						</div>");
document.writeln("						<strong>11层1121-187</strong>");
document.writeln("						<div><span>海淀区中关村大街1号</span></div>");
document.writeln("					</div>");
document.writeln("					<div class=\'contact_mini\'>");
document.writeln("						<div class=\'contact_icon_email\'>");
document.writeln("							<i class=\'glyphicon glyphicon-envelope\' aria-hidden=\'true\'></i>");
document.writeln("						</div>");
document.writeln("						<strong>kwd@kwangda.com</strong>");
document.writeln("						<div><span>随时欢迎您的来信</span></div>");
document.writeln("					</div>");
document.writeln("					<div class=\'contact_mini\'>");
document.writeln("						<div class=\'contact_icon_tel\'>");
document.writeln("							<i class=\'glyphicon glyphicon-earphone\' aria-hidden=\'true\'></i>");
document.writeln("						</div>");
document.writeln("						<strong>13718345029</strong>");
document.writeln("						<div><span>周一~周五, 8:00 - 20:00</span></div>");
document.writeln("					</div>");
document.writeln("					<!--contact-->");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		<!--header nav start-->");
document.writeln("		<div class=\'navbar navbar-default\'>");
document.writeln("			<div class=\'container-fluid\'>");
document.writeln("				<div class=\'container\'>");
document.writeln("					<div class=\'responsive-navigation visible-sm visible-xs\'>");
document.writeln("						<a href=\'#nogo\' class=\'menu-toggle-btn\' onclick=\'showAndhideNavlist()\'>");
document.writeln("							<i class=\'glyphicon glyphicon-align-justify\' aria-hidden=\'true\'></i>");
document.writeln("						</a>");
document.writeln("					</div>");
document.writeln("					<div class=\'main-navigation\'>");
document.writeln("						<div class=\'logo visible-sm visible-xs\'>");
document.writeln("							<a href=\'http://www.kwangda.com\'><img src=\'images/head foot/logo.png\' alt=\'科旺达\'></a>");
document.writeln("						</div>");
document.writeln("						<div class=\'main-nav visible-md visible-lg\'>");
document.writeln("							<ur class=\'nav_inner sf-js-enabled sf-arrows\'>");
document.writeln("								<li class=\'index\'><a href=\'index.html\'>首页</a></li>");
document.writeln("								<li class=\'product\'><a href=\'product.html\'>产品中心</a></li>");
document.writeln("								<li class=\'case\'><a href=\'case.html\'>客户案例</a></li>");
document.writeln("								<li class=\'solution\'><a href=\'solution.html\'>解决方案</a></li>");
document.writeln("								<li class=\'news\'><a href=\'news.html\'>新闻专栏</a></li>");
document.writeln("								<li class=\'aptitude\'><a href=\'aptitude.html\'>企业资质</a></li>");
document.writeln("								<li class=\'about\'><a href=\'about.html\'>关于我们</a></li>");
document.writeln("								<li class=\'contact\'><a href=\'contact.html\'>联系我们</a></li>");
document.writeln("							</ur>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("	</div>");